#!/usr/bin/env python3
"""Generate <worktrees>/Caddyfile from the port registry and (optionally) reload Caddy.

Each serve-mode workspace becomes pretty, port-less URLs (suffix from config,
default `localhost`):
    http://<task>.<suffix>            -> the primary frontend of the task
    http://<repo>.<task>.<suffix>     -> that specific repo

Caddy listens on :80 and reverse-proxies to the dev server's real port, rewriting
the Host header to `localhost` so dev servers' host checks pass unchanged. Chrome
resolves *.localhost to 127.0.0.1 itself — no /etc/hosts, no DNS.

Usage (run from anywhere inside the workspace, or pass --root):
    caddyfile.py            # (re)write <worktrees>/Caddyfile
    caddyfile.py --reload   # also push it to the running Caddy via the admin API
"""
import json
import os
import shutil
import subprocess
import sys

import config

HEADER = "# AUTO-GENERATED by the `feature` skill (caddyfile.py) — do not edit by hand.\n"


def load_ports(cfg):
    path = os.path.join(config.worktrees_root(cfg), ".ports.json")
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        return json.load(f)


def block(hosts, port):
    names = " ".join(f"http://{h}" for h in hosts)
    return (
        f"{names} {{\n"
        f"\treverse_proxy 127.0.0.1:{port} {{\n"
        f"\t\theader_up Host localhost\n"
        f"\t}}\n"
        f"}}\n"
    )


def render(cfg, ports):
    px = config.proxy(cfg)
    suffix = px["domain_suffix"]
    out = [HEADER, block([px["admin_host"]], px["admin_port"])]
    for task in sorted(ports):
        repos = ports[task]
        primary = config.primary_frontend(cfg, repos)
        for repo in sorted(repos):
            hosts = [f"{repo}.{task}.{suffix}"]
            if repo == primary:
                hosts.insert(0, f"{task}.{suffix}")
            out.append(block(hosts, repos[repo]))
    return "\n".join(out)


def write(cfg):
    path = os.path.join(config.worktrees_root(cfg), "Caddyfile")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(render(cfg, load_ports(cfg)))
    return path


def needs_setup(reason):
    """Tell the user, with a copy-pasteable command, how to enable pretty URLs.

    Printed whenever Caddy can't serve the workspace yet — whether it's not
    installed at all or installed-but-never-started. Surface this to the user
    verbatim; the reload is otherwise a silent no-op / cryptic failure.
    """
    setup = os.path.join(os.path.dirname(os.path.abspath(__file__)), "proxy-setup.sh")
    print(
        f"{reason}\n"
        f"  Pretty http://<task>.<suffix> URLs need a one-time Caddy setup (asks for sudo once):\n"
        f'      "{setup}"\n'
        f"  Until then, use the localhost:<port> URLs (kept in .feature.json)."
    )


def reload(cfg):
    caddy = shutil.which("caddy")
    if not caddy:
        needs_setup("caddy is not installed.")
        return
    brew_prefix = os.environ.get("HOMEBREW_PREFIX", "/opt/homebrew")
    cfg_path = os.path.join(brew_prefix, "etc", "Caddyfile")  # imports <worktrees>/Caddyfile
    r = subprocess.run([caddy, "reload", "--config", cfg_path], capture_output=True, text=True)
    if r.returncode == 0:
        print("caddy reloaded")
        return
    # Installed but the reload didn't take — almost always: Caddy was never started
    # as the root :80 service, i.e. proxy-setup.sh hasn't been run yet.
    tail = (r.stderr.strip().splitlines() or ["admin API unreachable"])[-1]
    needs_setup(f"caddy is installed but not serving yet (reload failed: {tail}).")


def main():
    args = sys.argv[1:]
    cfg = config.load(argv=args)
    path = write(cfg)
    print(f"wrote {path}")
    if "--reload" in args:
        reload(cfg)


if __name__ == "__main__":
    main()
